### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by rugk** [brennoflavio/nextcloud-alexa#1]
Here this has been referenced: https://help.nextcloud.com/t/alexa-skill-for-nextcloud/63049/4

Also a sibling project in German is here: https://github.com/rainu/alexa-skill/blob/master/cloud/README.md

Could we get more languages supported like at least English and maybe German (integrating the above)?

**Comment by brennoflavio** [comment]
Language support is something that you configure on the Alexa side. This project does not care about which language is being used, Alexa sends the same request regardless of the language being used.

The file intents.json in this repository is the starting point to customize to your needs. Inside each "intent" (like create a task, list tasks, etc) there is a "samples" section with the phrases that will make Alexa trigger that intent. Modify it before uploading this file to Alexa Developer Portal.

You may also change the project name in this file so you don't need to call a Brazilian word "Sabiá" every time.

So for example if you change the create task intent sample to be "create task {task_name}", you would say "Alexa ask Sabiá to create task x" and it will work normally. You can use any set of sentences you want.

If you do that please open a PR with your intent.json as a new file so other people can use it as well.

**Comment by rugk** [comment]
So maybe we could have a `intent.json` for different languages in a directory like `i18n` or so?

**Comment by tigger-developer** [comment]
Amazing - thanks guys, can't wait to try it!
